name: review

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: review-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        node: [16.x]
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: ✅ Lint code
        run: yarn lint --max-warnings=0

      - name: 🧪 Test code
        run: yarn test

      - name: 👷 Build code
        run: yarn clean && yarn build

      - name: 🕵️ Validate build
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol build/ | wc -l)" -gt "0" ]; then
            echo "⚠️ Build is outdated"
            echo "    > run 'yarn clean', 'yarn build', and commit changes"
            git diff
            exit 1
          fi

      - name: 🗂 Upload build
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: build
          path: build/
